config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  #authenticated :user do
  #  root to: "dashboard#home", as: :authenticated_root
  #end

  root to: "static_pages#home"

  namespace :dashboard do
    get "/home",       to: "dashboard#home"
    get "/timeline",   to: "dashboard#timeline"
    get "/search",     to: "dashboard#search"
    get "/tags",       to: "dashboard#tags"
    get "/help",       to: "dashboard#help"
    get "/hide_help",  to: "dashboard#hide_help"
    get "/graph",      to: "dashboard#graph"

    put "fulltext_search/page/:page", to: "dashboard#fulltext_search", as: "fulltext_search"
    put "timeline_search/page/:page", to: "dashboard#timeline_search", as: "timeline_search"
    put "graph_search/page/:page", to: "dashboard#graph_search", as: "graph_search"
    put "tags_search/page/:page", to: "dashboard#tags_search", as: "tags_search"
    put "tags_search_aat", to: "dashboard#tags_search_aat", as: "tags_search_aat"

    resources :messages

    resources :teams, only: [:new,:edit,:update,:create,:destroy] do
      member do
        post :unenroll, to: "teams#unenroll"
      end
    end

    namespace :teams do
      get :available, to: "teams#available"
      post :enroll, to: "teams#enroll"
    end
  end

  namespace :panel do
    resources :teams, only: [:show]
  end
end

app/models/lo.rb
class Lo
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :description, type: String
  field :available, type: Boolean, default: false

  belongs_to :user
  has_many :introductions, dependent: :delete
  has_many :exercises, dependent: :delete
  has_and_belongs_to_many :teams
  has_many :answers
  
  validates_presence_of :name, :description
  validates :name, uniqueness: true
  #validates :available, :inclusion => {:in => [true, false]}

  # Q: What is a 'page'?
  def pages_count
    pages.size
  end

  # Q: ?
  def pages_with_name
    i, e, page_count = 0, 0, 0

    pages.map do |page|
      if page.instance_of? Introduction
        i += 1
        page_count = i
      else
        e += 1
        page_count = e
      end
        { page_name: "#{page.class.model_name.human} #{page_count}: #{page.title}",
          type: page.class.to_s.downcase,
          page_collection: page_count-1
        }
      end
  end

  private

    def pages
      introductions_avaiable + exercises_avaiable
    end

    def exercises_avaiable
      exercises.where(available: true)
    end

    def introductions_avaiable
      introductions.where(available: true)
    end
end

app/models/team.rb
class Team
  include Mongoid::Document
  include Mongoid::Timestamps

  field :code, type: String
  field :name, type: String
  # Moped::BSON::ObjectId stores the id directly.
  field :owner_id, type: Moped::BSON::ObjectId
  # For some reason, for the word 'active' mongoid doesn't set a default value.
  # So it was changed to activated.
  field :activated, type: Boolean, default: true

  has_and_belongs_to_many :los
  has_and_belongs_to_many :users
  has_many :answers

  validates_presence_of :name, :code
  validates_uniqueness_of :name

  # Return scope not the records
  def self.search(search = "")
    return all.desc(:created_at) if search.empty?
    any_of(:name => search).desc(:created_at)
  end

  def add_user(user)
    users << user
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  before_save :generate_gravatar_hash

  # Include default devise modules. Others available are:
  # :recoverable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  # field :reset_password_token,   type: String
  # field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  field :name, :type => String
  field :gravatar
  field :admin, :type => Boolean, default: false
  field :prof, :type => Boolean, default: false
  field :super_admin, :type => Boolean, default: false
  field :guest, :type => Boolean, default: false
  field :show_help, :type => Boolean, default: true

  has_many :los, dependent: :delete
  has_many :answers, dependent: :delete
  has_many :retroaction_answers, dependent: :delete
  has_many :last_answers, dependent: :delete
  has_many :tags, dependent: :delete
  has_many :messages, dependent: :delete
  has_and_belongs_to_many :teams
  has_many :replies, dependent: :delete
  has_many :recommendations, dependent: :delete

  validates_presence_of :name
  validate :cannot_be_nil

  index({ email: "text" }, { background: true })

  def questions_without_tries
    questions = []

    self.teams.each do |t|
      t.los.each do |lo|
        lo.exercises.each do |ex|
          ex.questions.each do |q|
            if self.progress_question(t.id,q.id) == 0.0
              questions << [t,q]
            end
          end
        end
      end
    end
    questions
  end

  def last_try
    Answer.where(:user_id => self.id).desc(:created_at).first
  end

  def all_los
    if self.admin?
      Lo.all.asc(:name)
    else
      los = Array.new
      for team in self.all_teams do
        lo_ids = Answer.where(team_id:team.id).desc("lo_id").distinct("lo_id")
        if lo_ids.empty?
          los = los + team.los
        else
          los = los + (Lo.find(lo_ids) | team.los)
        end
      end

      if self.prof?
        los += self.los
      end

      los.uniq{|x| x.id}.sort_by{:name}
    end
  end

  def all_tags
    Tag.all.asc(:name)
  end

  def all_questions
    if self.admin?
      Question.all.asc(:title)
    else
      answered_questions = Answer.where(user_id:self.id).desc("question_id").distinct("question_id")
      questions = []
      unless answered_questions.empty?
        questions = Question.find(answered_questions)
      end

      question_ids = []
      for lo in self.all_los
        for ex in lo.exercises
          question_ids = question_ids + ex.question_ids
        end
      end

      questions = questions + Question.find(question_ids)
      questions.uniq{|x| x.id}.sort_by{|x| x.title}
    end
  end

  def last_messages_to_me(n)
    @messages = Message.any_of({:target_user_ids => self.id}, {:user_ids => self.id.to_s}).desc(:updated_at).desc(:updated_at).to_a + self.messages.keep_if {|x| x['new_flag_user_id'] }
    @messages.sort { |x,y| y.updated_at <=> x.updated_at}
  end

  def number_of_new_messages
    Message.any_of(:new_flag_user_ids => self.id).count + self.messages.keep_if {|x| x['new_flag_user_id'] }.count
  end

  def student?
    if self.prof? && (not self.admin?)
      return false
    end
    return true
  end

  # Return teams according user privilege level.
  def all_teams
    if admin?
      Team.all.asc(:name).to_a
    else
      # Q: shoul i realy put teams.asc('name')? That isn't right, according
      # other methods like 'all_teams_id'.
      Team.where(owner_id: id).asc('name').to_a + teams.asc('name')
    end
  end

  # Return teams id according user privilege level.
  def all_teams_id
    if admin?
      Team.all.pluck(:id)
    else
      Team.where(owner_id: id).pluck(:id)
    end
  end

  # Return users according privilege level.
  def all_students
    if admin?
      User.all.asc(:name).to_a
    else
      user_teams = Team.where(owner_id: id).asc('name').to_a
      users = user_teams.each.inject([self]) { |array, team| array = array + team.users }
      users.uniq.sort_by(&:name)
    end
  end

  # Add the user to a team.
  def add_team(team)
    teams << team
  end

  private

     # Custom validation for nil value
     def cannot_be_nil
       errors.add(:admin, "cannot be nil") if admin.nil?
       errors.add(:super_admin, "cannot be nil") if super_admin.nil?
     end

    # Gravatar URLs are based on an MD5 hash
    def generate_gravatar_hash
      self.gravatar = Digest::MD5.hexdigest(self.email)
    end
end

app/controllers/dashboard/dashboard_controller.rb
class Dashboard::DashboardController < ApplicationController
  layout 'dashboard'

  def home
    @boxes = []
		@last_messages = current_user.last_messages_to_me(4)

    if current_user.prof?
			@recommendations = Recommendation.all_from(current_user.id.to_s)#.shuffle.first(10)

			num_students = 0
			num_students_correct_answers = 0
			num_students_wrong_answers = 0
			team_ids = Team.where(owner_id:current_user.id.to_s).pluck(:id)
			team_ids.each do |team_id|
				t = Team.find(team_id.to_s)
				num_students = num_students + t.user_ids.count
				num_students_correct_answers = num_students_correct_answers + Answer.where(:team_id => t.id.to_s, :correct => true).count
				num_students_wrong_answers = num_students_wrong_answers + Answer.where(:team_id => t.id.to_s, :correct => false).count
			end

			num_wrong_answers = Answer.where(user_id: current_user.id,:correct => false).count
			num_correct_answers = Answer.where(user_id: current_user.id,:correct => true).count

      @boxes << {:color => "bg-orange", :value => team_ids.count, :title => "Número de turmas", :has_link? => false, :icon => "fa fa-book"}
      @boxes << {:color => "bg-aqua", :value => num_students, :title => "Número de alunos", :has_link? => false, :icon => "fa fa-users"}
      @boxes << {:color => "bg-red", :value => num_students_wrong_answers, :title => "Número de respostas incorretas", :has_link? => false, :icon => "fa fa-times"}
      @boxes << {:color => "bg-green", :value => num_students_correct_answers, :title => "Número de respostas corretas", :has_link? => false, :icon => "fa fa-check"}

			@last_answers = Answer.in(team_id: team_ids).desc(:created_at).limit(10)
			@last_comments = Comment.in(team_id: team_ids).desc('created_at')[0..4]
		else
			@last_answers = Answer.where(user_id: current_user.id).desc(:created_at)[0..4]
			last_try = current_user.last_try
			num_wrong_answers = Answer.where(:user_id => current_user.id, :correct => false).count
			num_correct_answers = Answer.where(:user_id => current_user.id, :correct => true).count
			num_questions_without_tries = current_user.questions_without_tries.count
			num_teams = current_user.teams.count

			@boxes << {:color => "bg-red", :value => num_wrong_answers, :title => "Número de respostas incorretas", :has_link? => false, :icon => "fa fa-times"}
			@boxes << {:color => "bg-green", :value => num_correct_answers, :title => "Número de respostas corretas", :has_link? => false, :icon => "fa fa-check"}
			@boxes << {:color => "bg-orange", :value => num_questions_without_tries, :title => "Número de questões sem tentativas", :has_link? => false, :icon => "fa fa-warning"}
			@boxes << {:color => "bg-blue", :value => num_teams, :title => "Número de turmas matriculadas", :has_link? => false, :icon => "fa fa-book"}
			unless last_try.nil?
				@boxes << {:color => ( last_try.correct ? "bg-green" : "bg-red"), :value => last_try.question.title.truncate(10), :title => "Última tentativa", :has_link? => true, :icon => "fa " + (last_try.correct ? "fa-check" : "fa-times"), :link => panel_team_user_lo_question_answer_path(last_try.team_id,last_try.user_id,last_try.lo_id,last_try.question_id,last_try.id) }
			end
			@last_comments = Comment.where(target_user_id: current_user.id ).desc('created_at')[0..4]
    end

		@boxes.shuffle!
	end

  def timeline
    init_search
  end

  def search
    init_search
  end

  def tags
    init_search
  end

  def init_search
    @teams = current_user.all_teams
    @questions = current_user.all_questions
    @los = current_user.all_los
    @users = current_user.all_students
    @tags = current_user.all_tags
  end

  def help
  end

  def timeline_search
    @as = Answer.search(params,current_user).entries
    @total = @as.count
    @as = @as.first(50)
    @timeline_items = Answer.make_timeline(@as)
    @params=params

    Log.log_search_timeline(current_user.id,params)
    render 'timeline_search_result'
  end

  def tags_search
		@as = Answer.search(params,current_user).entries
		@total = @as.count
		@as = @as.first(50)
    #@as_aat = Answer.search_aat(params,current_user)
		@params =params

		Log.log_search_tag(current_user.id,params)
    render 'tags_search_result'
  end

	def tags_search_aat
		@as_aat = Answer.search_aat(params,current_user)
		@total = @as_aat.count
		@as = @as_aat.first(50)
		render 'tags_search_aat_result'
	end

  def fulltext_search
		if params.has_key?(:page)
			page = params[:page]
		else
			page = 1
		end
    @as = Answer.search(params,current_user,page)
    @button_add = true
    @button_add = false unless params.has_key?(:button_add)
		@params =params

		Log.log_search_simple(current_user.id,params)

    render 'search_result'
  end

  def graph
    init_search
		Log.log_graph_view(current_user.id)
  end

  def graph_search
		@as = [Answer.last] #Answer.search(params,current_user).entries
		@total = @as.count
		#@as = @as.first(50)
		@params =params

		Log.log_search_graph(current_user.id,params)

    #render partial: 'graph_search_result'

    respond_to do |format|
      format.html { render partial: 'graph_search_result' }
      format.js { render 'graph_search_result' }
    end
  end

	def hide_help
		current_user.show_help = false
		current_user.save
	end
end

app/controllers/dashboard/messages_controller.rb
class Dashboard::MessagesController < ApplicationController
end

app/controllers/dashboard/teams_controller.rb
class Dashboard::TeamsController < ApplicationController
  before_action :authenticate_user!
  before_action :verify_prof, :only =>[:new, :update, :edit, :create,:destroy]
  before_action :can_edit?, :only =>[:update, :edit, :destroy]

  def can_edit?
    unless current_user.id.to_s == Team.find(params[:id]).owner_id.to_s || current_user.admin?
      render_401
    end
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(params[:team])
    @team.owner_id = current_user.id
    respond_to do |format|
      if @team.save
        format.html { redirect_to dashboard_teams_available_path, notice: 'Turma criada com sucesso.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    @team = Team.find(params[:id])

    respond_to do |format|
      if @team.update_attributes(params[:team])
        format.html { redirect_to panel_team_path(@team.id), notice: 'Turma atualizada com sucesso.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def enroll
    t = Team.find(params[:team][:id])
    unless t.users.include?(current_user)
      if t.code == params[:password]
        t.users << current_user

        t.save!
      else
        @wrong_code_team_id = t.id
      end
    end
    #@teams = Team.all
    @teams = Team.where(active: true)

    render "available"
  end

  def unenroll
    @team = Team.find(params[:id])

    if @team.users.include?(current_user)
      @team.user_ids = @team.user_ids - [current_user.id]
      @team.save!
    end

    redirect_to dashboard_teams_available_path
  end

  def destroy
    @team = Team.find(params[:id])

    if @team.owner_id == current_user.id
      @team.destroy
    end

    redirect_to dashboard_teams_available_path
  end

  def available
    @teams = Team.where(active: true)
    @teams_unavailable = Team.where(active: false)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/dashboard/_menu.html.erb
<!-- sidebar menu: : style can be found in sidebar.less -->
<ul class="sidebar-menu">

    <li class="<%= raw "active" if controller.class == Dashboard::DashboardController && controller.action_name == "home" %>">
        <%= link_to dashboard_home_path do %>
            <i class="fa fa-home"></i> <span>Home</span>
        <% end %>
    </li>

<% if current_user.prof? %>
    <li class="<%= raw "active" if controller.class == Dashboard::DashboardController && controller.action_name == "graph" %>">
        <%= link_to dashboard_graph_path do %>
          <i class="fa fa-code-fork"></i> <span>Grafo de Manipulação</span>
        <% end %>
    </li>
<% end %>

    <li class="<%= raw "active" if controller.class == Dashboard::DashboardController && controller.action_name == "timeline" %>">
        <%= link_to dashboard_timeline_path do %>
            <i class="fa fa-clock-o"></i> <span>Linha do Tempo</span>
        <% end %>
    </li>

    <li class="<%= raw "active" if controller.class == Dashboard::DashboardController && controller.action_name == "search" %>">
        <%= link_to dashboard_search_path do %>
            <i class="fa fa-search"></i> <span>Busca</span>
        <% end %>
    </li>
<% if current_user.prof? %>
    <li class="<%= raw "active" if controller.class == Dashboard::DashboardController && controller.action_name == "tags" %>">
        <%= link_to dashboard_tags_path do %>
            <i class="fa fa-tags"></i> <span>Tags</span>
        <% end %>
    </li>
<% end %>

    <li class="<%= raw "active" if controller.class == Dashboard::MessagesController %>">
        <%= link_to dashboard_messages_path do %>
            <i class="fa fa-envelope"></i> <span>Mensagens</span>
        <% end %>
    </li>

  <% if current_user.prof? %>
    <li>
        <a href="/los" target="_blank"><i class="fa fa-pencil-square-o"></i> <span>Meus O.A.'s</span></a>
    </li>
  <% end %>

<% if current_user.prof? %>
  <li class="<%= raw "active" if controller.class == Dashboard::TeamsController %>">
      <%= link_to dashboard_teams_available_path do %>
          <i class="fa fa-users"></i> <span>Turmas</span>
      <% end %>
  </li>
<% else %>
    <li class="<%= raw "active" if controller.class == Dashboard::TeamsController %>">
        <%= link_to dashboard_teams_available_path do %>
            <i class="fa fa-users"></i> <span>Turmas Disponíveis</span>
        <% end %>
    </li>
<% end %>

    <% # sorry about the next few lines =/ %>
    <% my_teams = Team.where(owner_id: current_user.id).asc('name') %>
    <% teams = current_user.teams.asc('name') %>
    <% others = Array.new %>
    <% if current_user.admin? %>
      <% others = Team.all.asc('name').entries - my_teams %>
    <% end %>

    <% unless my_teams.empty? %>
      <li class="treeview">
        <a href="#">
            <i class="fa fa-users"></i>
            <span>Minhas Turmas</span>
            <i class="fa fa-angle-left pull-right"></i>
        </a>

        <ul class="treeview-menu">
          <% my_teams.each do |t| %>
            <li><%= link_to t.name, panel_team_path(t.id), :style=>"margin-left:10px;" %></li>
          <% end %>
        </ul>
      </li>
    <% end %>

<% if current_user.admin? %>
    <% unless others.empty? %>
      <li class="treeview">
        <a href="#">
            <i class="fa fa-users"></i>
            <span>Outras Turmas</span>
            <i class="fa fa-angle-left pull-right"></i>
        </a>

        <ul class="treeview-menu">
          <% others.each do |t| %>
            <li>
              <%= link_to panel_team_path(t.id), :style=>"margin-left:10px;" do %>
                <i class="fa fa-angle-double-right"></i> <%= t.name %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </li>
    <% end %>
<% end %>

<% if current_user.student? %>
    <li class="treeview">
      <a href="#">
          <i class="fa fa-check-square-o"></i>
          <span>Turmas Matriculadas</span>
          <i class="fa fa-angle-left pull-right"></i>
      </a>

      <ul class="treeview-menu">
        <% teams.each do |t| %>
          <li><%= link_to t.name, panel_team_path(t.id), :style=>"margin-left:10px;" %></li>
        <% end %>
      </ul>
    </li>
<% end %>

    <li class="<%= raw "active" if controller.class == Dashboard::DashboardController && controller.action_name == "help" %>">
      <%= link_to dashboard_help_path do %>
        <i class="fa fa-question-circle"></i> Ajuda
      <% end %>
    </li>


    <!--
    <li>
        <a href="pages/widgets.html">
            <i class="fa fa-th"></i> <span>Widgets</span> <small class="badge pull-right bg-green">new</small>
        </a>
    </li>
    -->
    <!--
    <li class="treeview">
        <a href="#">
            <i class="fa fa-bar-chart-o"></i>
            <span>Charts</span>
            <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
            <li><a href="pages/charts/morris.html"><i class="fa fa-angle-double-right"></i> Morris</a></li>
            <li><a href="pages/charts/flot.html"><i class="fa fa-angle-double-right"></i> Flot</a></li>
            <li><a href="pages/charts/inline.html"><i class="fa fa-angle-double-right"></i> Inline charts</a></li>
        </ul>
    </li>
    -->
</ul>

app/views/dashboard/dashboard/_recommendation.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="box box-solid" style="border: 1px solid lightgray;">

      <% case recommendation.type %>
      <% when "questao_com_mais_incorretas" %>

        <div class="box-header">
            <h3 class="box-title">Questões com mais tentativas incorretas<br><small><%= Team.find(recommendation.item['team_id']).name if recommendation.item.has_key?('team_id') %></small></h3>
            <div class="box-tools pull-right">
                <button class="btn btn-default btn-sm" data-widget="remove"><i class="fa fa-times"></i></button>
            </div>
        </div>
        <div class="box-body">
          <p>
            A questão <%= Question.find(recommendation.item['question_id']).title %> é uma das que possui mais tentativas incorretas na turma <%= Team.find(recommendation.item['team_id']).name %>.
          </p>

          <p>
            Recomendamos a análise de alguma das seguintes respostas para os alunos desta turma:

            <% recommendation.item['answer_ids'][0..4].each do |answer_id| %>
              <% a = Answer.find(answer_id.to_s) %>
              <ul>
                <li>
                  <%= a.user.name + " @ " + a.question.title + " #" + a.try_number.to_s %>
                  <span class='label label-default answer-btn' style='cursor:pointer;' data-id="<%= a.id %>"> <i class='fa fa-eye'></i></span>
                </li>
              </ul>
            <% end %>
          </p>

          <p>
            <%= link_to new_dashboard_message_path+build_message_link(recommendation) do %>
              <%= button_tag raw("<i class='fa fa-share'></i> Repassar recomendação aos alunos"), :class => "btn btn-primary" %>
            <% end %>
          </p>
        </div><!-- /.box-body -->

      <% when "alunos_com_mais_incorretas" %>

        <div class="box-header">
            <h3 class="box-title">Alunos com mais tentativas incorretas<br><small><%= Team.find(recommendation.item['team_id']).name if recommendation.item.has_key?('team_id') %></small></h3>
            <div class="box-tools pull-right">
                <button class="btn btn-default btn-sm" data-widget="remove"><i class="fa fa-times"></i></button>
            </div>
        </div>
        <div class="box-body">
          <p>
            Estes são os alunos da turma <%= Team.find(recommendation.item['team_id']).name %> com mais tentativas incorretas.
            <ul>
              <% recommendation.item['user_ids'].each_index do |i| %>
                <li>
                  <% user_id = recommendation.item['user_ids'][i] %>
                  <% u = User.find(user_id) %>
                  <%= u.name + " (" + u.email + ") - " + recommendation.item['count'][i].to_s + " tentativs incorretas" %>
                </li>
              <% end %>
            </ul>
          </p>

          <p>
            <%= link_to new_dashboard_message_path+build_message_link(recommendation) do %>
              <%= button_tag raw("<i class='fa fa-share'></i> Repassar recomendação aos alunos"), :class => "btn btn-primary" %>
            <% end %>
          </p>
        </div><!-- /.box-body -->

      <% when "alunos_sem_resposta" %>

        <div class="box-header">
            <h3 class="box-title">Alunos sem participação<br><small><%= Team.find(recommendation.item['team_id']).name if recommendation.item.has_key?('team_id') %></small></h3>
            <div class="box-tools pull-right">
                <button class="btn btn-default btn-sm" data-widget="remove"><i class="fa fa-times"></i></button>
            </div>
        </div>
        <div class="box-body">
          <p>
            Um grupo de <%= recommendation.item['user_ids'].count %> alunos da turma <%= Team.find(recommendation.item['team_id']).name %> não realizou nenhuma tentativa.
            São eles:

            <ul>
              <% recommendation.item['user_ids'].each do |user_id| %>
                <li>
                  <% u = User.find(user_id) %>
                  <%= u.name + " (" + u.email + ")" %>
                </li>
              <% end %>
            </ul>
          </p>

          <p>
            <%= link_to new_dashboard_message_path+build_message_link(recommendation) do %>
              <%= button_tag raw("<i class='fa fa-share'></i> Repassar recomendação aos alunos"), :class => "btn btn-primary" %>
            <% end %>
          </p>
        </div><!-- /.box-body -->

      <% when "resposta_para_grupo" %>

        <div class="box-header">
            <h3 class="box-title">Recomendação de resposta para grupo de alunos<br><small><%= Team.find(recommendation.item['team_id']).name if recommendation.item.has_key?('team_id') %></small></h3>
            <div class="box-tools pull-right">
                <button class="btn btn-default btn-sm" data-widget="remove"><i class="fa fa-times"></i></button>
            </div>
        </div>
        <div class="box-body">
          <p>
            Um grupo de <%= recommendation.item['user_ids'].count %> alunos possui semelhanças nas respostas erradas para a questão <%= Question.find(recommendation.item['question_id']).title %>.
          </p>

          <p>
            Recomendamos a análise de alguma das seguintes respostas para este grupo de alunos:

            <% recommendation.item['answer_ids'][0..4].each do |answer_id| %>
              <% a = Answer.find(answer_id.to_s) %>
              <ul>
                <li>
                  <%= a.user.name + " @ " + a.question.title + " #" + a.try_number.to_s %>
                  <span class='label label-default answer-btn' style='cursor:pointer;' data-id="<%= a.id %>"> <i class='fa fa-eye'></i></span>
                </li>
              </ul>
            <% end %>
          </p>

          <ul style="display:none;" class="recommendation_users" data-recommendation-id="<%= recommendation.id %>">
            <% recommendation.item['user_ids'].each do |user_id| %>
              <li>
                <% u = User.find(user_id) %>
                <%= u.name + " (" + u.email + ")" %>
              </li>
            <% end %>
          </ul>

          <p>
            <%= link_to new_dashboard_message_path+build_message_link(recommendation)+"&recom=true" do %>
              <%= button_tag raw("<i class='fa fa-share'></i> Repassar recomendação aos alunos"), :class => "btn btn-primary" %>
            <% end %>
          </p>
        </div><!-- /.box-body -->
      <% end %>
    </div>
  </div>
</div>

app/views/dashboard/dashboard/_search_result.html.erb
<div class="row">
  <div id="search-result-count" class="col-md-12 text-center" style="margin-bottom:20px;">
    <%= as.count %> respostas encontradas.<br>
    <%= paginate(as) %>
    <%= filter_in_words(@params) %>
  </div>
</div>

<%= render :partial => "dashboard/answers/answer_card", :locals => {:answers => as, :button_tag => false, :n => 4, :button_add => button_add} %>