config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  #authenticated :user do
  #  root to: "dashboard#home", as: :authenticated_root
  #end

  root to: "static_pages#home"

  namespace :dashboard do
    get "/home",       to: "dashboard#home"
    get "/timeline",   to: "dashboard#timeline"
    get "/search",     to: "dashboard#search"
    get "/tags",       to: "dashboard#tags"
    get "/help",       to: "dashboard#help"
    get "/hide_help",  to: "dashboard#hide_help"
    get "/graph",      to: "dashboard#graph"

    put "fulltext_search/page/:page", to: "dashboard#fulltext_search", as: "fulltext_search"
    put "timeline_search/page/:page", to: "dashboard#timeline_search", as: "timeline_search"
    put "graph_search/page/:page", to: "dashboard#graph_search", as: "graph_search"
    put "tags_search/page/:page", to: "dashboard#tags_search", as: "tags_search"
    put "tags_search_aat", to: "dashboard#tags_search_aat", as: "tags_search_aat"

    resources :messages

    resources :teams, only: [:new,:edit,:update,:create,:destroy] do
      member do
        post :unenroll, to: "teams#unenroll"
      end
    end

    namespace :teams do
      get :available, to: "teams#available"
      post :enroll, to: "teams#enroll"
    end
  end

  namespace :panel do
    resources :teams, only: [:show]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render "shared/head_content" %>
  </head>

  <body>
    <%= render 'shared/header' %>

    <div class="container clearfix">
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
    <head>
      <%= render "shared/head_content" %>
    </head>
    <body class="skin-black">
      <div id="farmaAlgModals">
        <%= yield :modals %>
      </div>

      <div id="farmaAlgShowModals">

      </div>

        <!-- header logo: style can be found in header.less -->
        <header class="header">
            <%= link_to raw("FARMA-ALG <small style='font-size: 65%;'>#{@subdomain}</small>"), dashboard_home_path, :class => "logo" %>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Esconder menu</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-right">
                    <ul class="nav navbar-nav">
                        <!-- Messages: style can be found in dropdown.less-->
                        <li class="dropdown messages-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-envelope"></i>
                                <% unless  @n_new_messages == 0 %>
                                  <span class="label label-success"><%= @n_new_messages %></span>
                                <% end %>

                            </a>
                            <ul class="dropdown-menu">
                                <% unless  @n_new_messages == 0 %>
                                  <li class="header">Você tem <%= @n_new_messages %> novas mensagens</li>
                                <% end %>
                                <li>
                                    <ul class="menu">
                                      <% @messages_to_me_top.each do |m| %>

                                        <li>
                                            <a href="<%= dashboard_message_path(m) %>">
                                                <div class="pull-left">
                                                    <img src="http://www.gravatar.com/avatar/<%= m.user.gravatar%>" class="img-circle" alt="Imagem do usuário"/>
                                                </div>
                                                <h4>
                                                    <%= truncate(m.subject) %>
                                                </h4>
                                                <p><%= truncate(m.content) %></p>
                                                <h4>
                                                  <% if current_user.is_message_new?(m) %>
                                                    <span class="badge bg-green">nova</span>
                                                  <% end %>
                                                  <% if m.has_recommendation? %>
                                                    <span><i class="fa fa-paperclip"></i> </span>
                                                  <% end %>
                                                  <small><i class="fa fa-clock-o"></i> <%= time_ago_in_words m.updated_at %></small>
                                                </h4>
                                            </a>
                                        </li>
                                      <% end %>
                                    </ul>
                                </li>
                                <li class="footer"><a href="<%= dashboard_messages_path %>">Ver todas as mensagens</a></li>
                            </ul>
                        </li>


                        <!-- Notifications: style can be found in dropdown.less -->
                        <!--
                        <li class="dropdown notifications-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-warning"></i>
                                <span class="label label-warning">10</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="header">You have 10 notifications</li>
                                <li>
                                    <ul class="menu">
                                        <li>
                                            <a href="#">
                                                <i class="ion ion-ios7-people info"></i> 5 new members joined today
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="footer"><a href="#">View all</a></li>
                            </ul>
                        </li>
                        -->

                        <!-- Tasks: style can be found in dropdown.less -->
                        <!--
                        <li class="dropdown tasks-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-tasks"></i>
                                <span class="label label-danger">9</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="header">You have 9 tasks</li>
                                <li>
                                    <ul class="menu">
                                        <li>
                                            <a href="#">
                                                <h3>
                                                    Design some buttons
                                                    <small class="pull-right">20%</small>
                                                </h3>
                                                <div class="progress xs">
                                                    <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                                        <span class="sr-only">20% Complete</span>
                                                    </div>
                                                </div>
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="footer">
                                    <a href="#">View all tasks</a>
                                </li>
                            </ul>
                        </li>
                        -->


                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="glyphicon glyphicon-user"></i>
                                <span><%= current_user.name %> <i class="caret"></i></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="user-header bg-light-blue">
                                    <img src="http://www.gravatar.com/avatar/<%= current_user.gravatar%>" class="img-circle" alt="User Image" />
                                    <p>
                                        <%= current_user.name %> <%= raw "Administrador" if current_user.admin? %> <%= raw "Professor" if current_user.prof? && !current_user.admin?%>
                                        <small>Último acesso em <%= current_user.last_sign_in_at.strftime("%d/%m/%Y às %H:%M:%S") %></small>
                                    </p>
                                </li>

                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="/users/edit" class="btn btn-default btn-flat">Meus dados</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="/users/sign_out" data-method="delete" class="btn btn-default btn-flat">Sair</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>


        <div class="wrapper row-offcanvas row-offcanvas-left">
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="left-side sidebar-offcanvas">
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar">

                    <!-- Sidebar user panel -->
                    <div class="user-panel">
                        <div class="pull-left image">
                            <img src="http://www.gravatar.com/avatar/<%= current_user.gravatar%>" class="img-circle" alt="Imagem do Usuário" />
                        </div>
                        <div class="pull-left info">
                            <p>Olá, <%= current_user.name %></p>

                            <!--<a href="#"><i class="fa fa-circle text-success"></i> Online</a>-->
                        </div>
                    </div>

                    <!-- search form -->
                    <!--
                    <form action="#" method="get" class="sidebar-form">
                        <div class="input-group">
                            <input type="text" name="q" class="form-control" placeholder="Search..."/>
                            <span class="input-group-btn">
                                <button type='submit' name='seach' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    </form>
                    -->

                    <!-- menu -->
                    <%= render "dashboard/dashboard/menu" %>

                </section>
                <!-- /.sidebar -->
            </aside>

            <!-- Right side column. Contains the navbar and content of the page -->
            <aside class="right-side">
              <%= yield %>
            </aside><!-- /.right-side -->
        </div><!-- ./wrapper -->


    </body>
</html>